new-release: error out if the RELEASE file was not generated for some reason
This may happen for example when there's a syntax error in the XML
(e.g. forgot to escape some chars in the features list) or the
build system in www failed for some reason (e.g. because it has
been a while since autogen was run last and automake has been
upgraded since).

diff --git a/bin/new-release b/bin/new-release
--- a/bin/new-release
+++ b/bin/new-release
@@ -185,7 +185,13 @@ make
 
 release=htdocs/releases/$module/$version
 echo "Copying RELEASE"
-cp $release $moduledir/RELEASE
+cp $release $moduledir/RELEASE || {
+  echo "Error copying $release $moduledir/RELEASE."
+  echo "Maybe there was a problem creating $release , maybe because"
+  echo "there is a syntax error in $release.xml or some other problem"
+  echo "occured when rebuilding www/htdocs/releases/$module"
+  exit 1
+}
 
 echo "Press Enter to update NEWS with information from RELEASE"
 read
