documentation: add env var to skip git pull on cached module checkouts
Skip the git pull on the cached plugin module checkouts with the
plugin .xml files if the GST_WWW_SKIP_DOC_CHECKOUT_UPDATES
environment variable is set.

diff --git a/src/htdocs/documentation/Makefile.am b/src/htdocs/documentation/Makefile.am
--- a/src/htdocs/documentation/Makefile.am
+++ b/src/htdocs/documentation/Makefile.am
@@ -19,10 +19,14 @@ plugins.xml: checkoutdir
 	    git clean -f -d -x || { \
 	      echo "Cleaning $$m checkout failed"; exit 1; \
 	    } ; \
-	    echo "$$m checkout: updating..."; \
-	    git pull || { \
-	      echo "Updating $$m checkout failed"; exit 1; \
-	    } ; \
+	    if test "x$$GST_WWW_SKIP_DOC_CHECKOUT_UPDATES" != "x"; then \
+	      echo "$$m checkout: skipping update (GST_WWW_SKIP_DOC_CHECKOUT_UPDATES is set)"; \
+	    else \
+	      echo "$$m checkout: updating..."; \
+	      git pull || { \
+	        echo "Updating $$m checkout failed"; exit 1; \
+	      } ; \
+	    fi; \
 	    popd >/dev/null; \
 	  else \
 	    echo "$$m checkout: creating (cloning)"; \
