documentation: reuse git checkouts for documentation
Instead of doing a fresh git clone of all our modules everytime
you do 'make', keep a checkout cache around and update it.

diff --git a/src/htdocs/documentation/Makefile.am b/src/htdocs/documentation/Makefile.am
--- a/src/htdocs/documentation/Makefile.am
+++ b/src/htdocs/documentation/Makefile.am
@@ -1,15 +1,42 @@
 built_pages = index.html licensing.html rtp.html plugins.html splitup.html gstreamer010.html
 
-plugins.xml:
+CHECKOUT_DIR = $(abs_top_builddir)/cache/plugin-inspect-checkouts
+
+checkoutdir:
+	echo "Check plugin documentation checkout directory $(CHECKOUT_DIR)"; \
+	mkdir -p $(CHECKOUT_DIR) || { \
+	  echo "Failed to create $(CHECKOUT_DIR)"; \
+	  exit 1; \
+	}
+
+# Note: using pushd/popd because GIT_DIR doesn't seem to work properly
+plugins.xml: checkoutdir
 	for m in gstreamer gst-plugins-base gst-plugins-good gst-plugins-ugly gst-plugins-bad gst-plugins-gl; do \
-	  rm -rf $$m-checkouts.git $$m\-checkouts\-plugins-inspect > /dev/null; \
-	  git clone --depth 1 git://anongit.freedesktop.org/gstreamer/$$m $$m-checkouts.git; \
-	  ln -s $$m-checkouts.git/docs/plugins/inspect $$m\-checkouts\-plugins-inspect; \
+	  moduledir=$(CHECKOUT_DIR)/$$m; \
+	  if [ -d $$moduledir ] ; then \
+	    pushd $$moduledir >/dev/null; \
+	    echo "$$m checkout: cleaning"; \
+	    git clean -f -d -x || { \
+	      echo "Cleaning $$m checkout failed"; exit 1; \
+	    } ; \
+	    echo "$$m checkout: updating..."; \
+	    git pull || { \
+	      echo "Updating $$m checkout failed"; exit 1; \
+	    } ; \
+	    popd >/dev/null; \
+	  else \
+	    echo "$$m checkout: creating (cloning)"; \
+	    git clone git://anongit.freedesktop.org/gstreamer/$$m $$moduledir || { \
+	      echo "git clone failed"; exit 1; \
+	    } ; \
+	  fi; \
+	  rm -f $$m\-checkouts\-plugins-inspect 2> /dev/null; \
+	  ln -s $$moduledir/docs/plugins/inspect $$m\-checkouts\-plugins-inspect; \
 	done
 	echo "<plugins>" > plugins.xml
 	cat */*.xml >> plugins.xml
 	echo "</plugins>" >> plugins.xml
-	rm -rf *-checkouts.git *-checkouts-plugins-inspect
+	rm -f *-checkouts-plugins-inspect
 
 plugins.xml-update:
 	rm -f plugins.xml
